[versions]
agp = "8.3.2"
kotlin = "2.0.0"
compose-plugin = "1.6.11"
compose-compiler = "1.5.12"
androidx-activityCompose = "1.9.0"
compose-material3 = "1.2.1"
android-compose = "1.6.8"
material = "1.12.0"

compileSdk = "34"
minSdk = "28"
targetSdk = "34"
versionName = "1.0"
versionCode = "1"

coroutine = "1.8.1"
ksp = "2.0.0-1.0.21" # https://github.com/google/ksp/releases
room = "2.7.0-alpha04"
sqlite = "2.5.0-alpha04"
koin = "3.5.6"
koin-compose = "1.1.5"
koin-ksp = "1.3.1"

junit = "4.13.2"
mockito = "2.19.0"

kermit = "2.0.3"
lifecycle = "2.8.0"
immutableCollection = "0.3.5"
serialization = "1.7.0-RC"
decompose = "3.0.0"

paging = "3.3.0-alpha02-0.5.1"
kotlinx-datetime = "0.6.0"
[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose-plugin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "android-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "android-compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "android-compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "android-compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutine-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-ksp-compiler = { group = "io.insert-koin", name = "koin-ksp-compiler", version.ref = "koin-ksp" }
koin-annotations = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koin-ksp" }
koin-compose = { group = "io.insert-koin", name = "koin-compose", version.ref = "koin-compose" }

koin-test = { group = "io.insert-koin", name = "koin-test" }
koin-test-junit = { group = "io.insert-koin", name = "koin-test-junit4" }
coroutine-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version = "1.8.0" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "immutableCollection" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

paging-common = { group = "app.cash.paging", name = "paging-common", version.ref = "paging" }
paging-compose = { group = "app.cash.paging", name = "paging-compose-common", version.ref = "paging" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
[bundles]
test = [
    "kotlin-test",
    "koin-test",
    "koin-test-junit",
    "coroutine-test",
    "mockito",
    "junit"
]
decompose = [
    "decompose",
    "decompose-compose"
]
[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

convention-kmp-library = { id = "convention.kmp.library", version = "1.0" }
convention-kmp-library-compose = { id = "convention.kmp.library.compose", version = "1.0" }
convention-kmp-application = { id = "convention.kmp.application", version = "1.0" }
convention-android-library-compose = { id = "convention.android.library.compose", version = "1.0" }
convention-kmp-library-room = { id = "convention.kmp.library.room", version = "1.0" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }